In [1]:
import pandas as pd
import re

with open(
    'WhatsApp Chat with Serious discussion.txt',
    'r',
    encoding='utf-8'
) as f:
    data = f.read()

pattern = r'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

messages = re.split(pattern, data)[1:]
dates = re.findall(pattern, data)

min_len = min(len(messages), len(dates))
messages = messages[:min_len]
dates = dates[:min_len]

df = pd.DataFrame({
    'message_date': dates,
    'user_message': messages
})

df['message_date'] = df['message_date'].str.replace(' - ', '')

# 🔹 7. Convert to datetime
df['message_date'] = pd.to_datetime(
    df['message_date'],
    format='%d/%m/%y, %H:%M',
    errors='coerce'
)

df.rename(columns={'message_date': 'date'}, inplace=True)

df['user_message'] = df['user_message'].str.replace('\n', ' ')
df['user_message'] = df['user_message'].str.strip()

users = []
msgs = []

for message in df['user_message']:
    entry = re.split(r'([\w\W]+?):\s', message)

    if entry[1:]:  # user exists
        users.append(entry[1])
        msgs.append(entry[2])
    else:
        users.append('group_notification')
        msgs.append(entry[0])

df['user'] = users
df['message'] = msgs

df = df[['date', 'user', 'message']]

df.head()

,date,user,message
0,2026-01-24 23:18:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,2026-01-24 23:18:00,group_notification,You created this group
2,2026-01-24 23:18:00,group_notification,Bushra🌸 and Shreya 🫠 were added
3,2026-01-24 23:18:00,Aditi,Guyszss
4,2026-01-24 23:18:00,Aditi,Sunooooo

In [2]:
df['year'] = df['date'].dt.year
df.head()

,date,user,message,year
0,2026-01-24 23:18:00,group_notification,Messages and calls are end-to-end encrypted. O...,2026
1,2026-01-24 23:18:00,group_notification,You created this group,2026
2,2026-01-24 23:18:00,group_notification,Bushra🌸 and Shreya 🫠 were added,2026
3,2026-01-24 23:18:00,Aditi,Guyszss,2026
4,2026-01-24 23:18:00,Aditi,Sunooooo,2026

In [3]:
df['month_name'] = df['date'].dt.month_name()
df.head()

,date,user,message,year,month_name
0,2026-01-24 23:18:00,group_notification,Messages and calls are end-to-end encrypted. O...,2026,January
1,2026-01-24 23:18:00,group_notification,You created this group,2026,January
2,2026-01-24 23:18:00,group_notification,Bushra🌸 and Shreya 🫠 were added,2026,January
3,2026-01-24 23:18:00,Aditi,Guyszss,2026,January
4,2026-01-24 23:18:00,Aditi,Sunooooo,2026,January

In [4]:
df['day'] = df['date'].dt.day
df.head()

,date,user,message,year,month_name,day
0,2026-01-24 23:18:00,group_notification,Messages and calls are end-to-end encrypted. O...,2026,January,24
1,2026-01-24 23:18:00,group_notification,You created this group,2026,January,24
2,2026-01-24 23:18:00,group_notification,Bushra🌸 and Shreya 🫠 were added,2026,January,24
3,2026-01-24 23:18:00,Aditi,Guyszss,2026,January,24
4,2026-01-24 23:18:00,Aditi,Sunooooo,2026,January,24

In [5]:
df['hour'] = df['date'].dt.hour
df.head()

,date,user,message,year,month_name,day,hour
0,2026-01-24 23:18:00,group_notification,Messages and calls are end-to-end encrypted. O...,2026,January,24,23
1,2026-01-24 23:18:00,group_notification,You created this group,2026,January,24,23
2,2026-01-24 23:18:00,group_notification,Bushra🌸 and Shreya 🫠 were added,2026,January,24,23
3,2026-01-24 23:18:00,Aditi,Guyszss,2026,January,24,23
4,2026-01-24 23:18:00,Aditi,Sunooooo,2026,January,24,23

In [6]:
df['minute'] = df['date'].dt.minute
df.head()

,date,user,message,year,month_name,day,hour,minute
0,2026-01-24 23:18:00,group_notification,Messages and calls are end-to-end encrypted. O...,2026,January,24,23,18
1,2026-01-24 23:18:00,group_notification,You created this group,2026,January,24,23,18
2,2026-01-24 23:18:00,group_notification,Bushra🌸 and Shreya 🫠 were added,2026,January,24,23,18
3,2026-01-24 23:18:00,Aditi,Guyszss,2026,January,24,23,18
4,2026-01-24 23:18:00,Aditi,Sunooooo,2026,January,24,23,18

In [8]:
df[df['user'] == 'Aditi'].shape

(309, 8)